services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    restart: on-failure

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - ../frontend:/app  # Bind mount for live reloading
    ports:
      - "3000:3000"
    command: npm run dev  # Use dev mode for hot reloading